name = "Contexts"
uuid = "d092ff92-9eeb-4ab6-a2ac-bfa3dd0c68f9"
authors = ["Christian Gutsche"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[deps]
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"